# Generated by Django 3.1.5 on 2021-01-27 18:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('book_author', models.CharField(max_length=100, null=True)),
                ('date_of_publication', models.DateTimeField()),
                ('pages', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.AutoField(primary_key=True, serialize=False)),
                ('region_id', models.IntegerField()),
                ('school_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('principal', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='invalid phone number pattern', regex='^[0-9]{3}-[0-9]{4}$')])),
                ('address', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=25, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('book_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_details.book')),
                ('school_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_details.school')),
            ],
        ),
    ]
